### ISSUE TITLE
Ramsay St Extension significantly slows down drawing experience.

### ISSUE THREAD

**Issue by frankrolf** [typemytype/ramsayStreetRoboFontExtension#1]
Unfortunately. I wonder if the refresh could be made smarter?
I can imagine a mode that works only when the “fill” preview key is down, which would probably be more efficient than re-drawing the preview with each outline edit.

**Comment by frankrolf** [comment]
The Logger extension reveals that RamsaySt listens to every mouse drag, even when the preview is deactivated.

**Comment by typemytype** [comment]
dont subscribe to ever required notification and check there if the setting is on/off but instead remove the observer when its not required anymore...


see https://github.com/typemytype/ramsayStreetRoboFontExtension/blob/master/RamsaySt.roboFontExt/lib/ramsaySt.py#L17-L19

**Comment by typemytype** [comment]
upgrade to RF4 changes everything!
