### ISSUE TITLE
Preview always stays

### ISSUE THREAD

**Issue by supertype-de** [typemytype/ramsayStreetRoboFontExtension#5]
I can’t seem to toggle the preview, it always stays on

**Comment by typemytype** [comment]
the RamsaySt “Show Preview” toggles if the neighbours should be shown when preview is active or not, that seems to work fine here...

**Comment by supertype-de** [comment]
… but the outlines stay visible?







 
supertype.de <http://supertype.de/>
Prof. Jürgen Huber +49 179 39 66 327
instagram @supertype.de <https://www.instagram.com/supertype.de/>
twitter @supertype_de <https://twitter.com/supertype_de>

**Comment by typemytype** [comment]
this is how it should work:

https://user-images.githubusercontent.com/1190358/168297436-a1b13741-ce06-46c4-b38d-cc6339caa348.mov

**Comment by typemytype** [comment]
oke feature request: add a toggle to disable Ramsay completely
